version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: default
      - run:
          name: Build Backend Image
          command: |
            docker build -t tasksphere-backend:latest ./TaskSphere/backend
      - run:
          name: Build Frontend Image
          command: |
            docker build -t tasksphere-frontend:latest ./TaskSphere/frontend

workflows:
  build-and-test:
    jobs:
      - build
